const animeList = [
  "Naruto",
  "Attack on Titan",
  "One Piece",
  "Death Note",
  "Fullmetal Alchemist: Brotherhood",
  "Dragon Ball Z",
  "Dandadan",
  "Kaiju No. 8",
  "Demon Slayer: Kimetsu no Yaiba",
  "My Hero Academia",
  "Bleach",
  "Hunter x Hunter",
  "One Punch Man",
  "Tokyo Ghoul",
  "Code Geass",
  "Steins;Gate",
  "Cowboy Bebop",
  "Neon Genesis Evangelion",
  "Jujutsu Kaisen",
  "Sword Art Online",
  "JoJo's Bizarre Adventure",
  "Fairy Tail",
  "Re:Zero",
  "Mob Psycho 100",
  "Black Clover",
  "Haikyuu!!",
  "Your Lie in April",
  "Clannad",
  "Violet Evergarden",
  "Anohana",
  "A Silent Voice",
  "Your Name",
  "Spirited Away",
  "Howl's Moving Castle",
  "Princess Mononoke",
  "Grave of the Fireflies",
  "Ghost in the Shell",
  "Akira",
  "Hell's paradise",
  "Frieren",
  "Perfect Blue",
  "Paprika",
  "Death Parade",
  "Parasyte",
  "Erased",
  "Psycho-Pass",
  "Monster",
  "Serial Experiments Lain",
  "Berserk",
  "Vinland Saga",
  "Dororo",
  "Kingdom",
  "Dr. Stone",
  "The Promised Neverland",
  "Made in Abyss",
  "Mushishi",
  "Natsume's Book of Friends",
  "Barakamon",
  "Silver Spoon",
  "Great Teacher Onizuka",
  "Classroom of the Elite",
  "Assassination Classroom",
  "Kaguya-sama: Love is War",
  "Toradora!",
  "K-On!",
  "Lucky Star",
  "Nichijou",
  "Azumanga Daioh",
  "Daily Lives of High School Boys",
  "Ouran High School Host Club",
  "Fruits Basket",
  "Sailor Moon",
  "Cardcaptor Sakura",
  "Revolutionary Girl Utena",
  "Puella Magi Madoka Magica",
  "Little Witch Academia",
  "Cells at Work!",
  "Food Wars",
  "Yuri on Ice",
  "Free!",
  "Kuroko's Basketball",
  "Slam Dunk",
  "Initial D",
  "Yu Yu Hakusho",
  "Rurouni Kenshin",
  "Inuyasha",
  "Ranma ½",
  "Dragon Ball",
  "Pokémon",
  "Digimon Adventure",
  "Yu-Gi-Oh!",
  "Beyblade",
  "Bakugan",
  "Gintama",
  "Cyberpunk: Edgerunners",
  "The Apothecary Diaries",
  "Space Dandy",
  "Samurai Champloo",
  "Trigun",
  "Outlaw Star",
  "The Melancholy of Haruhi Suzumiya",
  "Angel Beats!",
  "Charlotte",
  "Plastic Memories",
  "I Want to Eat Your Pancreas",
  "Weathering With You",
  "5 Centimeters Per Second",
  "The Garden of Words",
  "Suzume",
  "Bubble",
  "Devilman: Crybaby",
  "Wolf Children",
  "The Boy and the Beast",
  "Summer Wars",
  "Tokyo magnitude 8.0",
  "Zankyou no Terror",
  "Banana Fish",
  "Golden kamuy",
  "91 Days",
  "Hellsing Ultimate",
  "Noragami",
  "Blue lock",
  "Blue Exorcist",
  "Akame ga Kill",
  "Elfen Lied",
  "Mirai Nikki",
  "No Game No Life",
  "Log Horizon",
  "Btooom!",
  "Deadman Wonderland",
  "Black Lagoon",
  "Tokyo Revengers",
  "Chainsaw Man",
  "Heavenly Delusion",
  "Pluto",
  "Ranking of Kings",
  "Odd Taxi",
  "Sonny Boy",
  "Ping Pong the Animation",
  "A Place Further Than the Universe",
  "Beastars",
  "FLCL",
  "Welcome to the NHK",
  "Kiznaiver",
  "Orange",
  "Horimiya",
  "Insomniacs After School",
  "Oshi no Ko",
];

export default animeList;
